---
title: "In-Class Exercise 5: Global and Local Measures of Spatial Autocorrelation using sfDep methods"
author: "Yung Qi Yang"

format: 
  html:
    code-fold: true
    code-summary: "Reveal Code"
    
execute: 
  eval: true
  echo: true
  warning: false
date: "`r Sys.Date()`"

toc: true
toc-location: left

progress: true
---

### Loading the required R-Packages

```{r}

pacman::p_load(sf, sfdep, sfdep, tidyverse, tmap)

```

### Importing the required datasets into the R-Environment

```{r}

hunan <- st_read("Data/Geospatial/Hunan", layer = "Hunan")

summary(hunan)

hunan2012 <- read_csv("Data/Aspatial/Hunan_2012.csv")

glimpse(hunan2012)

hunanGDPPC <- read_csv("Data/Aspatial/Hunan_GDPPC.csv")

glimpse(hunanGDPPC)

```

#### Appending the Hunan Aspatial data to the Hunan Geospatial *sf* object

```{r}
#| eval: false

hunan_GDPPC <- left_join(hunan, hunan2012) %>% 
  select(1:4, 7, 14)

write_rds(hunan_GDPPC, "Data/Geospatial/RDS/Hunan.rds")

```

#### Reading the combined Hunan spatial data

```{r}

hunan_GDPPC <- read_rds("Data/Geospatial/RDS/Hunan.rds")

```

### Visualising the GDPPC data in a choropleth map

```{r}

tmap_mode("plot")

tm_shape(hunan_GDPPC) +
  tm_fill("GDPPC", style = "quantile", palette = "Blues", title = "GDPPC") +
  tm_layout(main.title = "Distribution of GDP per capita by  county, Hunan province", main.title.position = "center", main.title.size = 1.2, legend.height = 0.45, legend.width = 0.35, frame = TRUE) +
  tm_borders(alpha = 0.5) +
  tm_compass(type = "8star", size = 2) +
  tm_scale_bar() +
  tm_grid(alpha = 0.2)

```

### Deriving the congruity weights using the ***QUEEN***'s method

```{r}

wm_q <- hunan_GDPPC %>% 
  mutate(nb = st_contiguity(geometry), wt = st_weights(nb, style = "W"), .before = 1)

```

### Computing the Moran's I statistic

```{r}

moranI <- global_moran(wm_q$GDPPC, wm_q$nb, wm_q$wt)

glimpse(moranI)

```

