project:
  type: website

website:
  title: "IS415 Course Website"
  navbar:
    left: 
    - text: "Hands-On Exercise"
      menu:
        - text: "Hands-On Exercise 1"
          href: "Hands-On_Exercise/Hands-On_Exercise_01/Hands-On_Exercise_01.html"
        - text: "Hands-On Exercise 2"
          href: "Hands-On_Exercise/Hands-On_Exercise_02/Hands-On_Exercise_02.html"
        - text: "Hands-On Exercise 3"
          href: "Hands-On_Exercise/Hands-On_Exercise_03/Hands-On_Exercise_03.html"
        - text: "Hands-On Exercise 4"
          href: "Hands-On_Exercise/Hands-On_Exercise_04/Hands-On_Exercise_04.html"
        - text: "Hands-On Exercise 5"
          href: "Hands-On_Exercise/Hands-On_Exercise_05/Hands-On_Exercise_05.html" 
    - text: "In-Class Exercise"
      menu:
        - text: "In-Class Exercise 2"
          href: "In-Class_Exercise/In-Class_Exercise_02/In-Class_Exercise_02.html"
        - text: "In-Class Exercise 3"
          href: "In-Class_Exercise/In-Class_Exercise_03/In-Class_Exercise_03.html"
        - text: "In-Class Exercise 4"
          href: "In-Class_Exercise/In-Class_Exercise_04/In-Class_Exercise_04.html"
        - text: "In-Class Exercise 5"
          href: "In-Class_Exercise/In-Class_Exercise_05/In-Class_Exercise_05.html"
    - text: "Take-Home Exercise"
      menu:
        - text: "Take-Home Exercise 1"
          href: "Take-Home_Exercise/Take-Home_Exercise_01/Take-Home_Exercise_01.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

