<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.549">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Yung Qi Yang">
<meta name="dcterms.date" content="2024-02-07">

<title>IS415 Course Website - Take-Home Exercise 1: Application of Spatial Point Patterns Analysis to discover the geographical distribution of Grab’s hailing services in Singapore</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">IS415 Course Website</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-hands-on-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Hands-On Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-hands-on-exercise">    
        <li>
    <a class="dropdown-item" href="../../Hands-On_Exercise/Hands-On_Exercise_01/Hands-On_Exercise_01.html">
 <span class="dropdown-text">Hands-On Exercise 1</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-On_Exercise/Hands-On_Exercise_02/Hands-On_Exercise_02.html">
 <span class="dropdown-text">Hands-On Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-On_Exercise/Hands-On_Exercise_03/Hands-On_Exercise_03.html">
 <span class="dropdown-text">Hands-On Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-On_Exercise/Hands-On_Exercise_04/Hands-On_Exercise_04.html">
 <span class="dropdown-text">Hands-On Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../Hands-On_Exercise/Hands-On_Exercise_05/Hands-On_Exercise_05.html">
 <span class="dropdown-text">Hands-On Exercise 5</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-in-class-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">In-Class Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-in-class-exercise">    
        <li>
    <a class="dropdown-item" href="../../In-Class_Exercise/In-Class_Exercise_02/In-Class_Exercise_02.html">
 <span class="dropdown-text">In-Class Exercise 2</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-Class_Exercise/In-Class_Exercise_03/In-Class_Exercise_03.html">
 <span class="dropdown-text">In-Class Exercise 3</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-Class_Exercise/In-Class_Exercise_04/In-Class_Exercise_04.html">
 <span class="dropdown-text">In-Class Exercise 4</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../In-Class_Exercise/In-Class_Exercise_05/In-Class_Exercise_05.html">
 <span class="dropdown-text">In-Class Exercise 5</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-take-home-exercise" role="button" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Take-Home Exercise</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-take-home-exercise">    
        <li>
    <a class="dropdown-item" href="../../Take-Home_Exercise/Take-Home_Exercise_01/Take-Home_Exercise_01.html">
 <span class="dropdown-text">Take-Home Exercise 1</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#preparing-the-r-environment-for-analysis" id="toc-preparing-the-r-environment-for-analysis" class="nav-link active" data-scroll-target="#preparing-the-r-environment-for-analysis">Preparing the R-Environment for analysis</a>
  <ul>
  <li><a href="#loading-the-necessary-r-packages" id="toc-loading-the-necessary-r-packages" class="nav-link" data-scroll-target="#loading-the-necessary-r-packages">Loading the necessary R-packages</a></li>
  </ul></li>
  <li><a href="#conducting-data-pre-processing-for-analysis" id="toc-conducting-data-pre-processing-for-analysis" class="nav-link" data-scroll-target="#conducting-data-pre-processing-for-analysis">Conducting data pre-processing for analysis</a>
  <ul>
  <li><a href="#importing-the-datasets-of-interest" id="toc-importing-the-datasets-of-interest" class="nav-link" data-scroll-target="#importing-the-datasets-of-interest">Importing the datasets of interest</a></li>
  <li><a href="#visualising-the-grab-posisi-trip-origins-data" id="toc-visualising-the-grab-posisi-trip-origins-data" class="nav-link" data-scroll-target="#visualising-the-grab-posisi-trip-origins-data">Visualising the Grab-Posisi trip origins data</a></li>
  <li><a href="#limiting-the-scope-of-the-study" id="toc-limiting-the-scope-of-the-study" class="nav-link" data-scroll-target="#limiting-the-scope-of-the-study">Limiting the scope of the study</a>
  <ul class="collapse">
  <li><a href="#extracting-the-cbd-polygons" id="toc-extracting-the-cbd-polygons" class="nav-link" data-scroll-target="#extracting-the-cbd-polygons">Extracting the CBD polygons</a></li>
  <li><a href="#visualising-the-geograpical-scope-of-study" id="toc-visualising-the-geograpical-scope-of-study" class="nav-link" data-scroll-target="#visualising-the-geograpical-scope-of-study">Visualising the geograpical scope of study</a></li>
  </ul></li>
  <li><a href="#filtering-down-the-grab-call-origins-data-to-match-the-study-area" id="toc-filtering-down-the-grab-call-origins-data-to-match-the-study-area" class="nav-link" data-scroll-target="#filtering-down-the-grab-call-origins-data-to-match-the-study-area">Filtering down the Grab call origins data to match the study area</a>
  <ul class="collapse">
  <li><a href="#visualising-the-origins-of-grab-trips-over-the-weekends-and-weekdays-in-the-central-region-of-singapore." id="toc-visualising-the-origins-of-grab-trips-over-the-weekends-and-weekdays-in-the-central-region-of-singapore." class="nav-link" data-scroll-target="#visualising-the-origins-of-grab-trips-over-the-weekends-and-weekdays-in-the-central-region-of-singapore.">Visualising the origins of Grab trips over the weekends and weekdays in the Central Region of Singapore.</a></li>
  <li><a href="#transforming-the-filtered-grab-origins-data-into-spatial-points-generic-sp-and-ppp-objects" id="toc-transforming-the-filtered-grab-origins-data-into-spatial-points-generic-sp-and-ppp-objects" class="nav-link" data-scroll-target="#transforming-the-filtered-grab-origins-data-into-spatial-points-generic-sp-and-ppp-objects">Transforming the filtered Grab origins data into <em>Spatial Points</em>, generic <em>sp</em> and <em>ppp</em> objects</a></li>
  <li><a href="#scaling-the-ppp-objects-to-km-for-more-interpretable-patterns-when-we-produce-the-kernel-density-estimates" id="toc-scaling-the-ppp-objects-to-km-for-more-interpretable-patterns-when-we-produce-the-kernel-density-estimates" class="nav-link" data-scroll-target="#scaling-the-ppp-objects-to-km-for-more-interpretable-patterns-when-we-produce-the-kernel-density-estimates">Scaling the <em>ppp</em> objects to “km” for more interpretable patterns when we produce the kernel density estimates</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#conducting-and-analysing-kernel-density-estimation" id="toc-conducting-and-analysing-kernel-density-estimation" class="nav-link" data-scroll-target="#conducting-and-analysing-kernel-density-estimation">Conducting and Analysing Kernel Density Estimation</a>
  <ul>
  <li><a href="#using-the-ppl-method-to-conduct-the-kernel-density-estimations" id="toc-using-the-ppl-method-to-conduct-the-kernel-density-estimations" class="nav-link" data-scroll-target="#using-the-ppl-method-to-conduct-the-kernel-density-estimations">Using the <strong><em>ppl</em></strong> method to conduct the Kernel Density Estimations</a></li>
  <li><a href="#using-the-adaptive-bandwidth-method-to-conduct-the-kernel-density-estimations" id="toc-using-the-adaptive-bandwidth-method-to-conduct-the-kernel-density-estimations" class="nav-link" data-scroll-target="#using-the-adaptive-bandwidth-method-to-conduct-the-kernel-density-estimations">Using the <strong><em>Adaptive Bandwidth</em></strong> method to conduct the Kernel Density Estimations</a></li>
  <li><a href="#conducting-the-clark-evans-test-for-spatial-point-pattern" id="toc-conducting-the-clark-evans-test-for-spatial-point-pattern" class="nav-link" data-scroll-target="#conducting-the-clark-evans-test-for-spatial-point-pattern">Conducting the Clark-Evans test for Spatial Point Pattern</a></li>
  </ul></li>
  <li><a href="#conducting-and-analysing-network-constrained-kernel-density-estimations" id="toc-conducting-and-analysing-network-constrained-kernel-density-estimations" class="nav-link" data-scroll-target="#conducting-and-analysing-network-constrained-kernel-density-estimations">Conducting and analysing Network-Constrained Kernel Density Estimations</a>
  <ul>
  <li><a href="#limiting-the-road-network-data-to-central-singapore" id="toc-limiting-the-road-network-data-to-central-singapore" class="nav-link" data-scroll-target="#limiting-the-road-network-data-to-central-singapore">Limiting the Road Network Data to Central Singapore</a>
  <ul class="collapse">
  <li><a href="#visualising-the-road-network-data-across-the-cbd" id="toc-visualising-the-road-network-data-across-the-cbd" class="nav-link" data-scroll-target="#visualising-the-road-network-data-across-the-cbd">Visualising the Road Network Data across the CBD</a></li>
  </ul></li>
  <li><a href="#preparing-the-lixel-objects-and-generating-the-line-centre-points" id="toc-preparing-the-lixel-objects-and-generating-the-line-centre-points" class="nav-link" data-scroll-target="#preparing-the-lixel-objects-and-generating-the-line-centre-points">Preparing the lixel objects and generating the line centre points</a></li>
  <li><a href="#performing-the-network-constrained-kernel-density-estimation" id="toc-performing-the-network-constrained-kernel-density-estimation" class="nav-link" data-scroll-target="#performing-the-network-constrained-kernel-density-estimation">Performing the Network Constrained Kernel Density Estimation</a>
  <ul class="collapse">
  <li><a href="#for-the-weekday-data" id="toc-for-the-weekday-data" class="nav-link" data-scroll-target="#for-the-weekday-data">For the Weekday Data:</a></li>
  <li><a href="#visualising-the-network-constrained-kernel-density-estimate-of-the-weekday-grab-data-over-an-interactive-openstreetmap-layer" id="toc-visualising-the-network-constrained-kernel-density-estimate-of-the-weekday-grab-data-over-an-interactive-openstreetmap-layer" class="nav-link" data-scroll-target="#visualising-the-network-constrained-kernel-density-estimate-of-the-weekday-grab-data-over-an-interactive-openstreetmap-layer">Visualising the Network Constrained Kernel Density Estimate of the Weekday Grab Data over an interactive <em>OpenStreetMap</em> layer</a></li>
  <li><a href="#for-the-weekend-data" id="toc-for-the-weekend-data" class="nav-link" data-scroll-target="#for-the-weekend-data">For the Weekend Data:</a></li>
  <li><a href="#visualising-the-network-constrained-kernel-density-estimate-of-the-weekend-grab-data-over-an-interactive-openstreetmap-layer" id="toc-visualising-the-network-constrained-kernel-density-estimate-of-the-weekend-grab-data-over-an-interactive-openstreetmap-layer" class="nav-link" data-scroll-target="#visualising-the-network-constrained-kernel-density-estimate-of-the-weekend-grab-data-over-an-interactive-openstreetmap-layer">Visualising the Network Constrained Kernel Density Estimate of the Weekend Grab Data over an interactive <em>OpenStreetMap</em> layer</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Take-Home Exercise 1: Application of Spatial Point Patterns Analysis to discover the geographical distribution of Grab’s hailing services in Singapore</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Yung Qi Yang </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 7, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="preparing-the-r-environment-for-analysis" class="level2">
<h2 class="anchored" data-anchor-id="preparing-the-r-environment-for-analysis">Preparing the R-Environment for analysis</h2>
<section id="loading-the-necessary-r-packages" class="level3">
<h3 class="anchored" data-anchor-id="loading-the-necessary-r-packages">Loading the necessary R-packages</h3>
<p>The following R-packages and their use case are as follows:</p>
<ul>
<li><strong>arrow:</strong> The Grab-Posisi datasets are stored in snappy.parquet format, so we will need to leverage upon the arrow package to read and write these data.</li>
<li><strong>tidyverse:</strong> To allow us to investigate, manipulate and write the datasets of interest in a readable manner. Also has great compatibility with <em>sf</em> objects.</li>
<li><strong>lubridate:</strong> To handle time format data and conversion of other data types into time formats.</li>
<li><strong>sf:</strong> Allows us to handle spatial data, specifically the master plan subzone and OpenStreetMap road network data.</li>
<li><strong>spatstat:</strong> Used to compute the Clark-Evan’s test and various Kernel Density Estimates in this report.</li>
<li><strong>maptools:</strong> Dependency for spatstat.</li>
<li><strong>tmap:</strong> For visualisation of the spatial data.</li>
<li><strong>htmlwidgets:</strong> Used to save interactive spatial data visualisations as HTML widgets to lessen the burden on Quarto when rendering.</li>
</ul>
<p>The <em>p_load()</em> functionfrom the pacman package is used to load the libraries and automatically install them for the user if they aren’t already installed.</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(sf, tidyverse, arrow, lubridate, tmap, maptools, spatstat, spNetwork, htmlwidgets)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
</section>
<section id="conducting-data-pre-processing-for-analysis" class="level2">
<h2 class="anchored" data-anchor-id="conducting-data-pre-processing-for-analysis">Conducting data pre-processing for analysis</h2>
<section id="importing-the-datasets-of-interest" class="level3">
<h3 class="anchored" data-anchor-id="importing-the-datasets-of-interest">Importing the datasets of interest</h3>
<p>For this report, 3 different datasets are of interest. <strong><em>Grab-Posisi</em></strong> (<em>parquet</em>) from <strong>Grab</strong> to obtain the spatial events of Grab trips, <strong><em>MPSZ2019</em></strong> (<em>shp</em>)from <strong>data.gov.sg</strong> to provide us with the geographical boundaries for our analysis and <strong><em>gis_osm_roads_free_1</em></strong> (<em>shp</em>) from <strong>OpenStreetMap</strong> to obtain the road networks for analysis.</p>
<section id="grab-posisi-data" class="level5">
<h5 class="anchored" data-anchor-id="grab-posisi-data">Grab-Posisi Data:</h5>
<p>The Grab-Posisi data is contained within 10 compartmentalised parquet files, thus, the <em>read_parquet()</em> function from the <em>Arrow</em> package is required. The files are loaded iteratively in a loop and immediately appended to each other without assignment using the <em>bind_rows()</em> function.</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>grab_df <span class="ot">&lt;-</span> <span class="fu">read_parquet</span>(<span class="st">"Data/Geospatial/GrabPosisi/part-00000-8bbff892-97d2-4011-9961-703e38972569.c000.snappy.parquet"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">9</span>) {</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  grab_df <span class="ot">&lt;-</span> grab_df <span class="sc">%&gt;%</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">bind_rows</span>(<span class="fu">read_parquet</span>(<span class="fu">paste0</span>(<span class="st">"Data/Geospatial/GrabPosisi/part-0000"</span>, <span class="fu">as.character</span>(i), <span class="st">"-8bbff892-97d2-4011-9961-703e38972569.c000.snappy.parquet"</span>)))</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>We can see that the Grab-Posisi dataset in its entirety at 30+ million rows is way too large for computation.</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(grab_df)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>grab_df<span class="sc">$</span>pingtimestamp <span class="ot">&lt;-</span> <span class="fu">as_datetime</span>(grab_df<span class="sc">$</span>pingtimestamp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><img src="Screenshots/Grab_Posisi_Data_Glimpse.png" class="img-fluid"></p>
<p>We will store the compiled Grab-Posisi just in case there is a need for its entirety in the future as there is spare memory on my drive for now.</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write_parquet</span>(grab_df, <span class="st">"Data/Geospatial/GrabPosisi/Grab_Posisi.parquet"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Luckily, as we are interested only in the analysis of the origins of Grab calls in Singapore, the Grab-Posisi data can be subset to reduce its size in the R-Environment to the necessary only. This is achieved using the <em>group_by()</em> function to sort each trip record by its ping time-stamp within the trip itself only. <em>filter()</em> is used to extract only the earliest, and therefore, the origin record while <em>mutate()</em> is used to extract the day of the week in which the trip occurred. The result is stored as an R-Data Structure (RDS) file using the <em>write_rds()</em> function to avoid re-computation in the future.</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>grab_origin_df <span class="ot">&lt;-</span> grab_df <span class="sc">%&gt;%</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(trj_id) <span class="sc">%&gt;%</span> </span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(pingtimestamp) <span class="sc">%&gt;%</span> </span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">row_number</span>() <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">weekday =</span> <span class="fu">wday</span>(pingtimestamp, <span class="at">label =</span> <span class="cn">TRUE</span>, <span class="at">abbr =</span> <span class="cn">TRUE</span>))</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(grab_origin_df)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="fu">paste</span>(<span class="st">"From:"</span>, <span class="fu">min</span>(grab_origin_df<span class="sc">$</span>pingtimestamp), <span class="st">"To:"</span>, <span class="fu">max</span>(grab_origin_df<span class="sc">$</span>pingtimestamp))</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(grab_origin_df, <span class="st">"Data/Geospatial/RDS/Grab_Origins_Posisi.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><img src="Screenshots/Grab_Origins_Data_Glimpse.png" class="img-fluid"></p>
<p>From a <em>glimpse()</em> of the subset data, we can see that the data set has been reduced considerably to 28,000 rows. This is still too large for kernel density estimations for my computer to handle, but for data wrangling and investigation purposes, it is good enough. As such, we will not rush to remove columns in case there is a need for them later especially as the main constraint in spatial computations is the number of events in the data.</p>
<p><img src="Screenshots/Grab_origins_daterange.png" class="img-fluid"></p>
<p>Additionally, we can see that the data exists for 14 days only between 8th April 2019 and 21st April 2019.</p>
<p>We save this subset data so that the code may be re-run in the future without going through the costly process of compiling and subsetting again.</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>grab_origin_df <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"Data/Geospatial/RDS/Grab_Origins_Posisi.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="singapore-master-plan-subzone-and-road-network-data" class="level5">
<h5 class="anchored" data-anchor-id="singapore-master-plan-subzone-and-road-network-data">Singapore Master Plan Subzone and Road Network Data</h5>
<p>Both the Singapore Master Plan Subzone (<strong><em>mpsz</em></strong>) and Road Network Data are spatial data which require the <em>sf</em> package to read in order to retain the spatial information contained. As such, we will use the <em>st_read()</em> function to read the data, and apply the <em>st_transform()</em> function to cast them to a consistent coordinate reference system (<strong>CRS</strong>) so that we may apply spatial analysis across both data. The <strong>CRS</strong> we will use is <u>SVY21</u>, which is specific for Singapore.</p>
<p>The Singapore Master Plan Subzone is loaded into the R-Environment below:</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>mpsz2019 <span class="ot">&lt;-</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_read</span>(<span class="st">"Data/Geospatial/MPSZ-2019"</span>, <span class="at">layer =</span> <span class="st">"MPSZ-2019"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3414</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Reading layer `MPSZ-2019' from data source 
  `C:\Users\yungq\Desktop\SMU Modules\Y4S1\Geospatial Analysis and Applications\IS415 Course Website\Take-Home_Exercise\Take-Home_Exercise_01\Data\Geospatial\MPSZ-2019' 
  using driver `ESRI Shapefile'
Simple feature collection with 332 features and 6 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 103.6057 ymin: 1.158699 xmax: 104.0885 ymax: 1.470775
Geodetic CRS:  WGS 84</code></pre>
</div>
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mpsz2019)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  SUBZONE_N          SUBZONE_C          PLN_AREA_N         PLN_AREA_C       
 Length:332         Length:332         Length:332         Length:332        
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
   REGION_N           REGION_C                  geometry  
 Length:332         Length:332         MULTIPOLYGON :332  
 Class :character   Class :character   epsg:3414    :  0  
 Mode  :character   Mode  :character   +proj=tmer...:  0  </code></pre>
</div>
</div>
<p>From the <em>summary()</em> of the data, we can see that it contains spatial polygon features, originally projected in <u>WGS84</u>, and we were successful in transforming the CRS to <u>SVY21</u> (or EPSG: 3414 equivalently).</p>
<p>Plotting the Master-Plan Subzone geospatial data with <em>tmap</em>’s <em>tm_polygons()</em> function for visualisation:</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>mpsz2019_plot <span class="ot">&lt;-</span> mpsz2019 <span class="sc">%&gt;%</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>() <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="at">col =</span> <span class="st">"lightyellow"</span>, <span class="at">border.col =</span> <span class="st">"navy"</span>) <span class="sc">+</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Singapore Master Plan Boundaries 2019"</span>, <span class="at">main.title.size =</span> <span class="dv">1</span>) <span class="sc">+</span> <span class="fu">tm_compass</span>(<span class="at">size =</span> <span class="dv">1</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_save</span>(<span class="at">tm =</span> mpsz2019_plot, <span class="st">"Screenshots/mpsz2019.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><img src="Screenshots/mpsz2019.png" class="img-fluid"></p>
<p>The <strong>OpenStreetMap</strong> (OSM) Road is loaded into the R-Environment below:</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>roads <span class="ot">&lt;-</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_read</span>(<span class="st">"Data/Geospatial/OSM"</span>, <span class="at">layer =</span> <span class="st">"gis_osm_roads_free_1"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3414</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(roads)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><img src="Screenshots/OSM_Road_Network.png" class="img-fluid"></p>
<p>Here, the data contains spatial linestrings, and like the mpsz data, is originally projected using WGS84 and successfully converted to SVY21. Also, although we know from the data source that the OSM road networks encompasses Singapore, Brunei and Malaysia, we can also tell from the R-outputs that it extends beyond Singapore’s borders. Compared to the mpsz data, its <u>bounding box</u> is clearly further extending. This also explains the vast number of features the data contains and its long reading time.</p>
<p>In the interest of computation times, we will subset the road networks to Singapore’s borders only. To do so, first we generate the Singaporean borders as a spatial polygon object using the <em>st_union()</em> function. We then employ the <em>st_intersection()</em> function on the generated outline of Singapore and the OSM road network to obtain the Singaporean road network only.</p>
<p>First, the coastal outline of Singapore is generated, and its result is saved as an RDS file with the <em>write_rds()</em> function to again avoid re-generation in the future.</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>coastal_outline <span class="ot">&lt;-</span> <span class="fu">st_union</span>(mpsz2019)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(coastal_outline, <span class="st">"Data/Geospatial/RDS/coastal_outline_sg.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>coastal_outline <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"Data/Geospatial/RDS/coastal_outline_sg.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>sg_coastal_outline_plot <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(coastal_outline) <span class="sc">+</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="at">col =</span> <span class="st">"white"</span>, <span class="at">border.col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="fl">1.7</span>) <span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="st">"Coastal Outine of Singapore 2019"</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_save</span>(sg_coastal_outline_plot, <span class="st">"Screenshots/sg_coastal_outline_plot.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><img src="Screenshots/sg_coastal_outline_plot.png" class="img-fluid"></p>
<p>Next, we subset the OSM road networks by using the <em>st_intersection()</em> function to constrict the spatial line objects to those within the coastal boundaries of Singapore as generated. Considering the long computation time due to the size of the OSM data, we will save the constricted road network as an RDS file.</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>roads_sg <span class="ot">&lt;-</span> <span class="fu">st_intersection</span>(coastal_outline, roads)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(roads_sg, <span class="st">"Data/Geospatial/RDS/sg_road_network.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>roads_sg <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"Data/Geospatial/RDS/sg_road_network.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Visualising the generated Singapore road networks with <em>tmap</em> using</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>mpsz_w_roads2019_plot <span class="ot">&lt;-</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(coastal_outline) <span class="sc">+</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="at">col =</span> <span class="st">"lightyellow"</span>, <span class="at">border.col =</span> <span class="st">"red"</span>, <span class="at">border.alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span> <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Singapore Road Network 2019"</span>, <span class="at">main.title.size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_compass</span>(<span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(roads_sg) <span class="sc">+</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_lines</span>()</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_save</span>(<span class="at">tm =</span> mpsz_w_roads2019_plot, <span class="st">"Screenshots/mpsz_w_roads2019.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><img src="Screenshots/mpsz_w_roads2019.png" class="img-fluid"></p>
<p>Here we can observe that there is an extensive road network present outside the mainland of Singapore in the dataset. Thus, we will need to remove them if mainland Singapore is the scope of the study, or if they fall within the scope regardless as they will otherwise affect network contrained kernel density estimates. This is as Grab is unlikely to operate outside the mainland especially on islands like Pulau Tekong, thus, impacting global kernel density estimates because of its low or zero local density.</p>
<p>First though, we should investigate the Grab-Posisi Data further as seen prior, we will need to reduce the scope of our analysis so that computations may be completed in a reasonable amount of time.</p>
</section>
<section id="transforming-the-grab-posisi-data-into-a-simple-features-object" class="level5">
<h5 class="anchored" data-anchor-id="transforming-the-grab-posisi-data-into-a-simple-features-object">Transforming the Grab-Posisi Data into a <em>simple features</em> object</h5>
<p>To investigate the Grab-Posisi data, we must first cast it into a <em>simple features</em> object so that R can recognise the coordinate fields in the dataset as spatial and not simply numeric data. The <em>st_as_af()</em> function is used for this purpose, specifying the longitude and latitudes in that order, and the CRS as WGS84 (or EPSG: 4326 equivalently) as the data are geographical coordinates. The CRS of the data is then transformed into SVY21 format using the <em>st_transform()</em> function by specifying the <em>crs</em> parameter to be 3414, the EPSG code for SVY21.</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>grab_origin_sf <span class="ot">&lt;-</span> grab_origin_df <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_as_sf</span>(<span class="at">coords =</span> <span class="fu">c</span>(<span class="st">"rawlng"</span>, <span class="st">"rawlat"</span>), <span class="at">crs =</span> <span class="dv">4326</span>) <span class="sc">%&gt;%</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_transform</span>(<span class="at">crs =</span> <span class="dv">3414</span>)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(grab_origin_sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>    trj_id          driving_mode          osname         
 Length:28000       Length:28000       Length:28000      
 Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character  
                                                         
                                                         
                                                         
                                                         
 pingtimestamp                        speed           bearing     
 Min.   :2019-04-08 00:09:26.00   Min.   :-1.000   Min.   :  0.0  
 1st Qu.:2019-04-11 08:48:29.25   1st Qu.: 3.590   1st Qu.: 90.0  
 Median :2019-04-15 00:08:48.00   Median : 9.945   Median :179.0  
 Mean   :2019-04-14 21:29:59.93   Mean   : 9.566   Mean   :172.5  
 3rd Qu.:2019-04-18 10:47:59.25   3rd Qu.:14.550   3rd Qu.:256.0  
 Max.   :2019-04-21 23:33:28.00   Max.   :30.949   Max.   :359.0  
                                                                  
    accuracy       weekday             geometry    
 Min.   :  1.000   Sun:3983   POINT        :28000  
 1st Qu.:  3.900   Mon:3975   epsg:3414    :    0  
 Median :  6.000   Tue:4008   +proj=tmer...:    0  
 Mean   :  7.617   Wed:4016                        
 3rd Qu.: 10.000   Thu:4008                        
 Max.   :728.000   Fri:4002                        
                   Sat:4008                        </code></pre>
</div>
</div>
<p>We can see from a the summary of the data that the casting of the grab origins data to a <em>simple features</em> object is successful and that a spatial point <em>geometry</em> column has been added to the data in place of <em>“rawlng”</em> and <em>“rawlat”</em>.</p>
</section>
<section id="transforming-the-grab-posisi-data-further-into-spatial-points-generic-sp-and-ppp-objects" class="level5">
<h5 class="anchored" data-anchor-id="transforming-the-grab-posisi-data-further-into-spatial-points-generic-sp-and-ppp-objects">Transforming the Grab-Posisi data further into <em>Spatial Points</em>, generic <em>sp</em> and <em>ppp</em> objects</h5>
<p>As we are using the spatstat package, we will need to cast our Grab trip origins events data from a <em>simple features</em> (<em>sf</em>) object to a <em>planar point pattern</em> (<em>ppp</em>) object to work with it.</p>
<p>To do so, we can utilise the <em>as_Spatial()</em> function from the sf package to first convert it into a spatial point dataframe which can then be further transformed to a generic <em>sp</em> object using the <em>as()</em> from the same package by specifying the object class to be “SpatialPoints”. This is required to safely convert an <em>sf</em> object to a <em>ppp</em> object as the <em>as()</em> function does not support casting an <em>sf</em> object to a <em>ppp</em> object directly. The resulting <em>sp</em> object is then computed as a <em>ppp</em> object using the <em>as()</em> function but this time specifying the new object class to be “ppp”.</p>
<p>The transformation process and a summary of each casting step are as follows:</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>grab_origin_spatial <span class="ot">&lt;-</span> grab_origin_sf <span class="sc">%&gt;%</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_Spatial</span>()</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(grab_origin_spatial)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Object of class SpatialPointsDataFrame
Coordinates:
                min      max
coords.x1  3628.243 49845.23
coords.x2 25198.140 49689.64
Is projected: TRUE 
proj4string :
[+proj=tmerc +lat_0=1.36666666666667 +lon_0=103.833333333333 +k=1
+x_0=28001.642 +y_0=38744.572 +ellps=WGS84 +towgs84=0,0,0,0,0,0,0
+units=m +no_defs]
Number of points: 28000
Data attributes:
    trj_id          driving_mode          osname         
 Length:28000       Length:28000       Length:28000      
 Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character  
                                                         
                                                         
                                                         
                                                         
 pingtimestamp                        speed           bearing     
 Min.   :2019-04-08 00:09:26.00   Min.   :-1.000   Min.   :  0.0  
 1st Qu.:2019-04-11 08:48:29.25   1st Qu.: 3.590   1st Qu.: 90.0  
 Median :2019-04-15 00:08:48.00   Median : 9.945   Median :179.0  
 Mean   :2019-04-14 21:29:59.93   Mean   : 9.566   Mean   :172.5  
 3rd Qu.:2019-04-18 10:47:59.25   3rd Qu.:14.550   3rd Qu.:256.0  
 Max.   :2019-04-21 23:33:28.00   Max.   :30.949   Max.   :359.0  
                                                                  
    accuracy       weekday   
 Min.   :  1.000   Sun:3983  
 1st Qu.:  3.900   Mon:3975  
 Median :  6.000   Tue:4008  
 Mean   :  7.617   Wed:4016  
 3rd Qu.: 10.000   Thu:4008  
 Max.   :728.000   Fri:4002  
                   Sat:4008  </code></pre>
</div>
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>grab_origin_sp <span class="ot">&lt;-</span> grab_origin_spatial <span class="sc">%&gt;%</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as</span>(<span class="st">"SpatialPoints"</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(grab_origin_sp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Object of class SpatialPoints
Coordinates:
                min      max
coords.x1  3628.243 49845.23
coords.x2 25198.140 49689.64
Is projected: TRUE 
proj4string :
[+proj=tmerc +lat_0=1.36666666666667 +lon_0=103.833333333333 +k=1
+x_0=28001.642 +y_0=38744.572 +ellps=WGS84 +towgs84=0,0,0,0,0,0,0
+units=m +no_defs]
Number of points: 28000</code></pre>
</div>
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>grab_origin_ppp <span class="ot">&lt;-</span> grab_origin_sp <span class="sc">%&gt;%</span>  </span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as</span>(<span class="st">"ppp"</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(grab_origin_ppp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Planar point pattern:  28000 points
Average intensity 2.473666e-05 points per square unit

Coordinates are given to 3 decimal places
i.e. rounded to the nearest multiple of 0.001 units

Window: rectangle = [3628.24, 49845.23] x [25198.14, 49689.64] units
                    (46220 x 24490 units)
Window area = 1131920000 square units</code></pre>
</div>
</div>
</section>
</section>
<section id="visualising-the-grab-posisi-trip-origins-data" class="level3">
<h3 class="anchored" data-anchor-id="visualising-the-grab-posisi-trip-origins-data">Visualising the Grab-Posisi trip origins data</h3>
<p>To visualise the Grab trip origins data we prepared, we can use the <em>tm_dots()</em> function. Additionally, as there are 28,000 event points located on a relatively small geographical area, we can expect the points to be dense enough such that we are likely to see clusters without being able to visually make out their densities or individual points.</p>
<p>To help with this problem, we can visualise the data using an interactive map style so that we may zoom into specific areas and reduce the density of our visualisation. Normally this can be achieved by specifying <em>tmap_mode()</em> to “view” but as such visualisations are large and computationally expensive, it is in our interest to build the in R and embed them as a HTML widget thus, avoiding building them during the render process. To do so, we leave it in “plot” mode in order to transform them to a <em>leaflet</em> object using the <em>tmap_leaflet()</em> function. The resulting <em>leaflet</em> object can then be saved as a HTML widget using the <em>saveWidget()</em> function from the <em>htmlwidgets</em> package.</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>grab_origins_interactive <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(grab_origin_sf) <span class="sc">+</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>, <span class="at">size =</span> <span class="fl">0.03</span>, <span class="at">col =</span> <span class="st">"green"</span>) <span class="sc">+</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Grab-Posisi Origin points across Singapore"</span>)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>grab_origins_interactive <span class="ot">=</span> <span class="fu">tmap_leaflet</span>(grab_origins_interactive)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="fu">saveWidget</span>(<span class="at">widget =</span> grab_origins_interactive, <span class="at">file =</span> <span class="st">"Screenshots/grab_origins_interactive.html"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<!--html_preserve-->
<iframe src="Screenshots/grab_origins_interactive.html" width="600" height="400">
</iframe>
<!--html_preserve-->
<p>If we zoom in, it appears that there are little to no overlaps of point coordinates in the data. This is to be expected for 2 reasons. First, pick-up locations are unlikely to fall in the exact same location especially when collected for 2 weeks only. Secondly, the data is very precise (to the cm) when considering that it exists on a country-wide scale. We know this as the data is precise to 2 decimal places when converted to SVY21 and SVY21 geographical points are listed in meters.</p>
<p>To be sure, we can use the following code to check for duplicated points.</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">any</span>(<span class="fu">duplicated</span>(grab_origin_ppp))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
<p>This is a good finding as it confirms that there is no need to account for point duplication in the dataset.</p>
<p>Now, we need to solve the next problem which is the scope of our analysis. To do so, we can look for general point clusters across Singapore which might be of interest to us. A quick visualisation using the coastal outline previously generated as the base layer is performed to help with this.</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>grab_origin_sg_plot <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(coastal_outline) <span class="sc">+</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="at">col =</span> <span class="st">"lightyellow"</span>, <span class="at">border.col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Origins of Grab Trips in Singapore (within Mainland only)"</span>) <span class="sc">+</span></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(grab_origin_sf) <span class="sc">+</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>(<span class="at">col =</span> <span class="st">"darkgreen"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>)</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_save</span>(grab_origin_sg_plot, <span class="st">"Screenshots/Grab_Origins_SG.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><img src="Screenshots/Grab_Origins_SG.png" class="img-fluid"></p>
<p>From the darker colouration, it appears that Grab calls in our data were much more concentrated in the central-southern part of Singapore than pretty much any other region. This of course makes sense as that region is where the central business district (CBD) lies, and considering the difference in cost of Grab vs.&nbsp;other forms of public transport, it should be expected that Grab customers are more likely fall within the CBD area especially towards the end of the workday.</p>
<p>Considering the size of the Grab origins data and the complexity of the road network, it makes sense to try to limit the area of study so our machines can handle the computations in reasonable time. Considering the spread of the data, the central region is chosen as our area of focus.</p>
</section>
<section id="limiting-the-scope-of-the-study" class="level3">
<h3 class="anchored" data-anchor-id="limiting-the-scope-of-the-study">Limiting the scope of the study</h3>
<section id="extracting-the-cbd-polygons" class="level4">
<h4 class="anchored" data-anchor-id="extracting-the-cbd-polygons">Extracting the CBD polygons</h4>
<p>Using the Urban Redevelopment Authority of Singapore’s (URA) definition of the CBD, the planning areas which makes it up are extracted from the mpsz spatial data. These polygons are identified using the “PLN_AREA_N” feature in the data, and extracted using base dataframe splicing methods and the %in% operator in R.</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>central_sg <span class="ot">&lt;-</span> mpsz2019[mpsz2019<span class="sc">$</span>PLN_AREA_N <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"DOWNTOWN CORE"</span>, <span class="st">"MARINA EAST"</span>, <span class="st">"MARINA SOUTH"</span>, <span class="st">"MUSEUM"</span>, <span class="st">"NEWTON"</span>, <span class="st">"ORCHARD"</span>, <span class="st">"OUTRAM"</span>, <span class="st">"RIVER VALLEY"</span>, <span class="st">"ROCHOR"</span>, <span class="st">"SINGAPORE RIVER"</span>, <span class="st">"STRAITS VIEW"</span>), ]</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(central_sg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>  SUBZONE_N          SUBZONE_C          PLN_AREA_N         PLN_AREA_C       
 Length:50          Length:50          Length:50          Length:50         
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
   REGION_N           REGION_C                  geometry 
 Length:50          Length:50          MULTIPOLYGON :50  
 Class :character   Class :character   epsg:3414    : 0  
 Mode  :character   Mode  :character   +proj=tmer...: 0  </code></pre>
</div>
</div>
<p>The spliced <em>sf</em> object is assigned to <em>central_sg</em> and a summary of the data reveals that it contains 50 spatial polygon objects. Much smaller than the 332 polygon features that were originally in the mpsz dataset.</p>
</section>
<section id="visualising-the-geograpical-scope-of-study" class="level4">
<h4 class="anchored" data-anchor-id="visualising-the-geograpical-scope-of-study">Visualising the geograpical scope of study</h4>
<p>To visualise the new geographical area of study:</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>central_region_plot <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(mpsz2019) <span class="sc">+</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="at">col =</span> <span class="st">"lightyellow"</span>, <span class="at">border.col =</span> <span class="st">"navy"</span>) <span class="sc">+</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Central Region of Singapore"</span>) <span class="sc">+</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(central_sg) <span class="sc">+</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="at">col =</span> <span class="st">"orange"</span>, <span class="at">border.col =</span> <span class="st">"red"</span>)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_save</span>(central_region_plot, <span class="st">"Screenshots/central_region_SG.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><img src="Screenshots/central_region_SG.png" class="img-fluid"></p>
<p>From the visualisation, we can confirm that the spliced polygons comprises of roughly the area of interest which we identified earlier and that we have reduced the boundaries of our data considerably (much more than the 332 → 50 polygon reduction would suggest).</p>
<p>Also, we can confirm that none of Singapore’s outer islands are involved in the focus area we have chosen, and as such we would not need to further narrow down the area to rid of any such polygons.</p>
<p>As the focus of the study is the CBD as a whole, and not specific planning areas within the CBD, it makes sense to recomputed the sliced data to consist of the outer boundaries of the CBD only. Like before, the <em>st_union()</em> function is used.</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>central_sg <span class="ot">&lt;-</span> <span class="fu">st_union</span>(central_sg)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>A visualisation of the computed boundary polygon can again be visualised by layering it upon the mpsz spatial data using multiple calls to the <em>tm_polygons()</em> function.</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>central_region_SG_outline <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(mpsz2019) <span class="sc">+</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="at">col =</span> <span class="st">"lightyellow"</span>, <span class="at">border.col =</span> <span class="st">"navy"</span>) <span class="sc">+</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Central Region of Singapore"</span>) <span class="sc">+</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(central_sg) <span class="sc">+</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="at">col =</span> <span class="st">"orange"</span>, <span class="at">border.col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_save</span>(central_region_SG_outline, <span class="st">"Screenshots/central_region_SG_outline.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><img src="Screenshots/central_region_SG_outline.png" class="img-fluid"></p>
</section>
</section>
<section id="filtering-down-the-grab-call-origins-data-to-match-the-study-area" class="level3">
<h3 class="anchored" data-anchor-id="filtering-down-the-grab-call-origins-data-to-match-the-study-area">Filtering down the Grab call origins data to match the study area</h3>
<p>Now that we have dictated the study area for the rest of the study, we will also need to trim down the Grab call origins data that we have. This can be achieve via the <em>st_intersection()</em> function to reduce the data to only those within the boundaries of the <em>central_sg</em> polygon we produced.</p>
<p>A further interesting point of study might be the difference in calls between the weekends and weekdays. As mentioned in the justification for choosing the CBD as the scope, we expect that most of the Grab call events occur as a result of office workers travelling home. Thus, as most offices are closed on the weekends, it will be interesting to examine the difference in call patterns during the work week vs.&nbsp;the weekends . To do so, we will break the data into 2 parts using the <em>weekday</em> column generated prior to identify calls that fall on the weekends.</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>grab_weekend <span class="ot">&lt;-</span> grab_origin_sf[grab_origin_sf<span class="sc">$</span>weekday <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Sun"</span>, <span class="st">"Sat"</span>), ]</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>grab_weekday <span class="ot">&lt;-</span> grab_origin_sf[<span class="sc">!</span>grab_origin_sf<span class="sc">$</span>weekday <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Sun"</span>, <span class="st">"Sat"</span>), ]</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>central_grab_weekend_sf <span class="ot">&lt;-</span> <span class="fu">st_intersection</span>(grab_weekend, central_sg)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>central_grab_weekday_sf <span class="ot">&lt;-</span> <span class="fu">st_intersection</span>(grab_weekday, central_sg)</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(central_grab_weekend_sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>    trj_id          driving_mode          osname         
 Length:698         Length:698         Length:698        
 Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character  
                                                         
                                                         
                                                         
                                                         
 pingtimestamp                        speed           bearing     
 Min.   :2019-04-13 00:31:23.00   Min.   :-1.000   Min.   :  0.0  
 1st Qu.:2019-04-13 16:50:57.00   1st Qu.: 3.417   1st Qu.: 53.0  
 Median :2019-04-14 14:02:41.00   Median : 8.527   Median :172.5  
 Mean   :2019-04-17 02:11:19.36   Mean   : 8.497   Mean   :172.9  
 3rd Qu.:2019-04-20 15:51:27.25   3rd Qu.:13.170   3rd Qu.:299.0  
 Max.   :2019-04-21 23:25:40.00   Max.   :24.620   Max.   :358.0  
                                                                  
    accuracy       weekday            geometry  
 Min.   :  2.000   Sun:308   POINT        :698  
 1st Qu.:  4.354   Mon:  0   epsg:3414    :  0  
 Median :  8.788   Tue:  0   +proj=tmer...:  0  
 Mean   : 10.932   Wed:  0                      
 3rd Qu.: 13.490   Thu:  0                      
 Max.   :100.000   Fri:  0                      
                   Sat:390                      </code></pre>
</div>
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(central_grab_weekday_sf)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>    trj_id          driving_mode          osname         
 Length:2335        Length:2335        Length:2335       
 Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character  
                                                         
                                                         
                                                         
                                                         
 pingtimestamp                        speed           bearing     
 Min.   :2019-04-08 00:09:48.00   Min.   :-1.000   Min.   :  0.0  
 1st Qu.:2019-04-10 09:36:16.50   1st Qu.: 2.631   1st Qu.: 48.5  
 Median :2019-04-12 22:38:39.00   Median : 7.583   Median :152.0  
 Mean   :2019-04-13 23:06:58.46   Mean   : 7.821   Mean   :166.7  
 3rd Qu.:2019-04-17 12:29:12.50   3rd Qu.:12.196   3rd Qu.:293.0  
 Max.   :2019-04-19 23:12:41.00   Max.   :26.160   Max.   :359.0  
                                                                  
    accuracy       weekday            geometry   
 Min.   :  2.000   Sun:  0   POINT        :2335  
 1st Qu.:  4.141   Mon:441   epsg:3414    :   0  
 Median :  8.576   Tue:454   +proj=tmer...:   0  
 Mean   : 11.581   Wed:457                       
 3rd Qu.: 13.000   Thu:540                       
 Max.   :728.000   Fri:443                       
                   Sat:  0                       </code></pre>
</div>
</div>
<p>A quick examination of the data shows that there were 2335 trips which originated on weekdays, and 698 calls on the weekends. In general, we can also expect around 25 less calls on Saturdays than during the work week and roughly 60 less calls on Sundays. Thursdays also generated the most calls at 540 trip originations happening on thursdays across the 2 weeks.</p>
<section id="visualising-the-origins-of-grab-trips-over-the-weekends-and-weekdays-in-the-central-region-of-singapore." class="level4">
<h4 class="anchored" data-anchor-id="visualising-the-origins-of-grab-trips-over-the-weekends-and-weekdays-in-the-central-region-of-singapore.">Visualising the origins of Grab trips over the weekends and weekdays in the Central Region of Singapore.</h4>
<p>To visualise the rough density patterns across the 2 different time periods in the CBD, we can employ the following code:</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>grab_central_weekday_plot <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(central_sg) <span class="sc">+</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="at">col =</span> <span class="st">"lightyellow"</span>, <span class="at">border.col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Origins of Weekday Grab Trips in Singapore (within Central Region only)"</span>, <span class="at">main.title.size =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(central_grab_weekday_sf) <span class="sc">+</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>(<span class="at">col =</span> <span class="st">"darkgreen"</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">size =</span> <span class="fl">0.5</span>)</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>grab_central_weekend_plot <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(central_sg) <span class="sc">+</span></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="at">col =</span> <span class="st">"lightyellow"</span>, <span class="at">border.col =</span> <span class="st">"blue"</span>, <span class="at">lwd =</span> <span class="fl">1.5</span>) <span class="sc">+</span></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Origins of Weekend Grab Trips in Singapore (within Central Region only)"</span>, <span class="at">main.title.size =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(central_grab_weekend_sf) <span class="sc">+</span></span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>(<span class="at">col =</span> <span class="st">"darkgreen"</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>, <span class="at">size =</span> <span class="fl">0.5</span>)</span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_save</span>(grab_central_weekday_plot, <span class="st">"Screenshots/grab_central_weekday_plot.png"</span>)</span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_save</span>(grab_central_weekend_plot, <span class="st">"Screenshots/grab_central_weekend_plot.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><img src="Screenshots/grab_central_weekday_plot.png" class="img-fluid"></p>
<p><img src="Screenshots/grab_central_weekend_plot.png" class="img-fluid"></p>
<p><u><em>tm_dots()</em></u> is used to identify the Grab trip origins and a reasonably low <em>alpha</em> value is specified to introduce transparency in the visualisation so that areas of denser events will stand out with deeper colours.</p>
<p>It appears that on the weekends, calls not only originate from the CBD less often. Although this is neither obvious nor interpretable from the visualisation alone as we are comparing 10 days of data vs.&nbsp;4 days worth. However, our quick investigation of the spliced data above does make this a reasonable observation to have here.</p>
<p>Additionally, it seems also that the geographical patterns in Grab calls also differ on the weekends and weekdays. On the weekdays the Grab trip origins appear to be more evenly distributed whilst being slightly more concentrated in the nothern regions of the CBD on the weekends with barely any calls from the center and southern parts during this period.</p>
</section>
<section id="transforming-the-filtered-grab-origins-data-into-spatial-points-generic-sp-and-ppp-objects" class="level4">
<h4 class="anchored" data-anchor-id="transforming-the-filtered-grab-origins-data-into-spatial-points-generic-sp-and-ppp-objects">Transforming the filtered Grab origins data into <em>Spatial Points</em>, generic <em>sp</em> and <em>ppp</em> objects</h4>
<p>As before with the <em>simple features</em> Grab data we need to transform the data to a <em>ppp</em> object if we want to conduct analysis on it using the <em>spatstats</em> package. To do so:</p>
<section id="for-the-weekend" class="level5">
<h5 class="anchored" data-anchor-id="for-the-weekend">For the Weekend:</h5>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>central_grab_weekend_spatial <span class="ot">&lt;-</span> central_grab_weekend_sf <span class="sc">%&gt;%</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_Spatial</span>()</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(central_grab_weekend_spatial)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Object of class SpatialPointsDataFrame
Coordinates:
               min      max
coords.x1 26935.13 31786.09
coords.x2 27890.04 32876.01
Is projected: TRUE 
proj4string :
[+proj=tmerc +lat_0=1.36666666666667 +lon_0=103.833333333333 +k=1
+x_0=28001.642 +y_0=38744.572 +ellps=WGS84 +towgs84=0,0,0,0,0,0,0
+units=m +no_defs]
Number of points: 698
Data attributes:
    trj_id          driving_mode          osname         
 Length:698         Length:698         Length:698        
 Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character  
                                                         
                                                         
                                                         
                                                         
 pingtimestamp                        speed           bearing     
 Min.   :2019-04-13 00:31:23.00   Min.   :-1.000   Min.   :  0.0  
 1st Qu.:2019-04-13 16:50:57.00   1st Qu.: 3.417   1st Qu.: 53.0  
 Median :2019-04-14 14:02:41.00   Median : 8.527   Median :172.5  
 Mean   :2019-04-17 02:11:19.36   Mean   : 8.497   Mean   :172.9  
 3rd Qu.:2019-04-20 15:51:27.25   3rd Qu.:13.170   3rd Qu.:299.0  
 Max.   :2019-04-21 23:25:40.00   Max.   :24.620   Max.   :358.0  
                                                                  
    accuracy       weekday  
 Min.   :  2.000   Sun:308  
 1st Qu.:  4.354   Mon:  0  
 Median :  8.788   Tue:  0  
 Mean   : 10.932   Wed:  0  
 3rd Qu.: 13.490   Thu:  0  
 Max.   :100.000   Fri:  0  
                   Sat:390  </code></pre>
</div>
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>central_grab_weekend_sp <span class="ot">&lt;-</span> central_grab_weekend_spatial <span class="sc">%&gt;%</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as</span>(<span class="st">"SpatialPoints"</span>)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(central_grab_weekend_sp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Object of class SpatialPoints
Coordinates:
               min      max
coords.x1 26935.13 31786.09
coords.x2 27890.04 32876.01
Is projected: TRUE 
proj4string :
[+proj=tmerc +lat_0=1.36666666666667 +lon_0=103.833333333333 +k=1
+x_0=28001.642 +y_0=38744.572 +ellps=WGS84 +towgs84=0,0,0,0,0,0,0
+units=m +no_defs]
Number of points: 698</code></pre>
</div>
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>central_grab_weekend_ppp <span class="ot">&lt;-</span> central_grab_weekend_sp <span class="sc">%&gt;%</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as</span>(<span class="st">"ppp"</span>)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(central_grab_weekend_ppp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Planar point pattern:  698 points
Average intensity 2.885876e-05 points per square unit

Coordinates are given to 3 decimal places
i.e. rounded to the nearest multiple of 0.001 units

Window: rectangle = [26935.13, 31786.09] x [27890.04, 32876.01] units
                    (4851 x 4986 units)
Window area = 24186800 square units</code></pre>
</div>
</div>
</section>
<section id="for-the-weekdays" class="level5">
<h5 class="anchored" data-anchor-id="for-the-weekdays">For the Weekdays:</h5>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>central_grab_weekday_spatial <span class="ot">&lt;-</span> central_grab_weekday_sf <span class="sc">%&gt;%</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_Spatial</span>()</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(central_grab_weekday_spatial)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Object of class SpatialPointsDataFrame
Coordinates:
               min      max
coords.x1 26902.48 32829.73
coords.x2 28050.48 33252.24
Is projected: TRUE 
proj4string :
[+proj=tmerc +lat_0=1.36666666666667 +lon_0=103.833333333333 +k=1
+x_0=28001.642 +y_0=38744.572 +ellps=WGS84 +towgs84=0,0,0,0,0,0,0
+units=m +no_defs]
Number of points: 2335
Data attributes:
    trj_id          driving_mode          osname         
 Length:2335        Length:2335        Length:2335       
 Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character  
                                                         
                                                         
                                                         
                                                         
 pingtimestamp                        speed           bearing     
 Min.   :2019-04-08 00:09:48.00   Min.   :-1.000   Min.   :  0.0  
 1st Qu.:2019-04-10 09:36:16.50   1st Qu.: 2.631   1st Qu.: 48.5  
 Median :2019-04-12 22:38:39.00   Median : 7.583   Median :152.0  
 Mean   :2019-04-13 23:06:58.46   Mean   : 7.821   Mean   :166.7  
 3rd Qu.:2019-04-17 12:29:12.50   3rd Qu.:12.196   3rd Qu.:293.0  
 Max.   :2019-04-19 23:12:41.00   Max.   :26.160   Max.   :359.0  
                                                                  
    accuracy       weekday  
 Min.   :  2.000   Sun:  0  
 1st Qu.:  4.141   Mon:441  
 Median :  8.576   Tue:454  
 Mean   : 11.581   Wed:457  
 3rd Qu.: 13.000   Thu:540  
 Max.   :728.000   Fri:443  
                   Sat:  0  </code></pre>
</div>
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>central_grab_weekday_sp <span class="ot">&lt;-</span> central_grab_weekday_spatial <span class="sc">%&gt;%</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as</span>(<span class="st">"SpatialPoints"</span>)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(central_grab_weekday_sp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Object of class SpatialPoints
Coordinates:
               min      max
coords.x1 26902.48 32829.73
coords.x2 28050.48 33252.24
Is projected: TRUE 
proj4string :
[+proj=tmerc +lat_0=1.36666666666667 +lon_0=103.833333333333 +k=1
+x_0=28001.642 +y_0=38744.572 +ellps=WGS84 +towgs84=0,0,0,0,0,0,0
+units=m +no_defs]
Number of points: 2335</code></pre>
</div>
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>central_grab_weekday_ppp <span class="ot">&lt;-</span> central_grab_weekday_sp <span class="sc">%&gt;%</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as</span>(<span class="st">"ppp"</span>)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(central_grab_weekday_ppp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Planar point pattern:  2335 points
Average intensity 7.573262e-05 points per square unit

Coordinates are given to 3 decimal places
i.e. rounded to the nearest multiple of 0.001 units

Window: rectangle = [26902.48, 32829.73] x [28050.48, 33252.24] units
                    (5927 x 5202 units)
Window area = 30832200 square units</code></pre>
</div>
</div>
<p>Again, summaries of each casting step are displayed to our purview.</p>
</section>
</section>
<section id="scaling-the-ppp-objects-to-km-for-more-interpretable-patterns-when-we-produce-the-kernel-density-estimates" class="level4">
<h4 class="anchored" data-anchor-id="scaling-the-ppp-objects-to-km-for-more-interpretable-patterns-when-we-produce-the-kernel-density-estimates">Scaling the <em>ppp</em> objects to “km” for more interpretable patterns when we produce the kernel density estimates</h4>
<p>As mentioned prior, the data is scaled in meters. This means that when we generate the kernel density estimates (KDE) we will be given densities which suggests that certain areas receive 0.0005 calls per meter<sup>2</sup> for instance as we are running a KDE across an entire country. This has very low interpretability, so we should re-scale the data points to km so that we can receive easy to understand density estimates when we conduct KDE.</p>
<p>To do so, we rely upon the <em>rescale()</em> function, parsing the conversion rate of 1000 to the function:</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>central_grab_weekend_ppp.km <span class="ot">&lt;-</span> <span class="fu">rescale</span>(central_grab_weekend_ppp, <span class="dv">1000</span>, <span class="st">"km"</span>)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>central_grab_weekday_ppp.km <span class="ot">&lt;-</span> <span class="fu">rescale</span>(central_grab_weekday_ppp, <span class="dv">1000</span>, <span class="st">"km"</span>)</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(central_grab_weekend_ppp.km)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Planar point pattern:  698 points
Average intensity 28.85876 points per square km

Coordinates are given to 6 decimal places

Window: rectangle = [26.93513, 31.78609] x [27.89004, 32.87601] km
                    (4.851 x 4.986 km)
Window area = 24.1868 square km
Unit of length: 1 km</code></pre>
</div>
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(central_grab_weekday_ppp.km)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Planar point pattern:  2335 points
Average intensity 75.73262 points per square km

Coordinates are given to 6 decimal places

Window: rectangle = [26.90248, 32.82973] x [28.05048, 33.25224] km
                    (5.927 x 5.202 km)
Window area = 30.8322 square km
Unit of length: 1 km</code></pre>
</div>
</div>
<p>Summaries of the Grab trip origins planar point pattern objects now show that the points have successfully been re-scaled to km.</p>
</section>
</section>
</section>
<section id="conducting-and-analysing-kernel-density-estimation" class="level2">
<h2 class="anchored" data-anchor-id="conducting-and-analysing-kernel-density-estimation">Conducting and Analysing Kernel Density Estimation</h2>
<section id="using-the-ppl-method-to-conduct-the-kernel-density-estimations" class="level3">
<h3 class="anchored" data-anchor-id="using-the-ppl-method-to-conduct-the-kernel-density-estimations">Using the <strong><em>ppl</em></strong> method to conduct the Kernel Density Estimations</h3>
<p>The <em>ppl</em> method is favoured here because the pre-emptive visualisation showed us that the call origins are generally spread out in multiple clusters over the week. As such, we do not use the <em>diggle</em> bandwidth method as we are not searching for a single cluster within a bunch of noise but rather multiple clusters.</p>
<p>The KDE are computed using the <em>density()</em> function from <em>spatstat</em>, specifying <em>bw.ppl</em> for the kernel bandwidth. Especially as there are large clusters near the edge of our project’s geographical boundaries observable from earlier visualisations, it is imperative that we correct for edge bias by specifying it to <u><em>TRUE</em></u>.</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">cex.main =</span> <span class="fl">0.7</span>)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>kde_central_grab_weekend_ppl_bw.km <span class="ot">&lt;-</span> <span class="fu">density</span>(central_grab_weekend_ppp.km, <span class="at">sigma=</span>bw.ppl, <span class="at">edge=</span><span class="cn">TRUE</span>, <span class="at">kernel=</span><span class="st">"gaussian"</span>)</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>kde_central_grab_weekday_ppl_bw.km <span class="ot">&lt;-</span> <span class="fu">density</span>(central_grab_weekday_ppp.km, <span class="at">sigma=</span>bw.ppl, <span class="at">edge=</span><span class="cn">TRUE</span>, <span class="at">kernel=</span><span class="st">"gaussian"</span>)</span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kde_central_grab_weekend_ppl_bw.km, <span class="at">main =</span> <span class="st">"Scaled Kernel Density Estimate of Grab Trip Origins in Central SG on Weekends (ppl)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-Home_Exercise_01_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kde_central_grab_weekday_ppl_bw.km, <span class="at">main =</span> <span class="st">"Scaled Kernel Density Estimate of Grab Trip Origins in Central SG on Weekdays (ppl)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-Home_Exercise_01_files/figure-html/unnamed-chunk-30-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From the produced KDE plots, we can confirm that the Grab trip origins are pretty evenly spread out in multiple clusters across the CBD on the weekdays. However, the trips are far more concentrated in the northern half of the CBD than we initially realised, with 2 big hotspots in there which stand out from the rest.</p>
</section>
<section id="using-the-adaptive-bandwidth-method-to-conduct-the-kernel-density-estimations" class="level3">
<h3 class="anchored" data-anchor-id="using-the-adaptive-bandwidth-method-to-conduct-the-kernel-density-estimations">Using the <strong><em>Adaptive Bandwidth</em></strong> method to conduct the Kernel Density Estimations</h3>
<p>An adaptive bandwidth method can also be applied to our kernel density estimates instead:</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">cex.main =</span> <span class="fl">0.7</span>)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>kde_central_grab_weekend_ppp_adaptive <span class="ot">&lt;-</span> <span class="fu">adaptive.density</span>(central_grab_weekend_ppp.km, <span class="at">method=</span><span class="st">"kernel"</span>)</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>kde_central_grab_weekday_ppp_adaptive <span class="ot">&lt;-</span> <span class="fu">adaptive.density</span>(central_grab_weekday_ppp.km, <span class="at">method=</span><span class="st">"kernel"</span>)</span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kde_central_grab_weekend_ppp_adaptive, <span class="at">main =</span> <span class="st">"Kernel Density Estimate of Grab Trip Origins in central SG on weekends (adaptive bandwidth)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-Home_Exercise_01_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(kde_central_grab_weekday_ppp_adaptive, <span class="at">main =</span> <span class="st">"Kernel Density Estimate of Grab Trip Origins in central SG on weekdays (adaptive bandwidth)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Take-Home_Exercise_01_files/figure-html/unnamed-chunk-31-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The adaptive KDE plots tells a similar story to when the <em>ppl</em> bandwidth method was applied. However, this time, the clustering of the origins of Grab trips towards the northern half of the CBD during the weekends are far more evident than before. In fact, when adapative bandwidth is applied, the southern half of the CBD is what can only be described as a cold-spot with barely any purple-ish colouration present. The evidence of multiple but well-spread out clusters across the CBD during the weekdays is more evident here than before as previously it seems like the hot-spots may have been briefly connected, here, the drop-off between each hot-spot is much more obvious.</p>
</section>
<section id="conducting-the-clark-evans-test-for-spatial-point-pattern" class="level3">
<h3 class="anchored" data-anchor-id="conducting-the-clark-evans-test-for-spatial-point-pattern">Conducting the Clark-Evans test for Spatial Point Pattern</h3>
<p>To conduct a Clark-Evans’ hypothesis test as to the randomness of the spatial point distribution of Grab trips in the CBD, we can utilise the <em>clarkevans.test()</em> function. Within the function, we can correct for edge bias again, especially now that we know from the KDE that we can expect the data to be heavily concentrated near the top during the weekends. <em>CDF</em> correction method is applied as recommended in the Clark-Evans documentation in R which suggests Donnelly correction for rectangular windows only.</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">clarkevans.test</span>(central_grab_weekday_ppp.km, <span class="at">correction=</span><span class="st">"cdf"</span>, <span class="at">alternative=</span><span class="fu">c</span>(<span class="st">"clustered"</span>), <span class="at">nsim=</span><span class="dv">99</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Clark-Evans test
    CDF correction
    Z-test

data:  central_grab_weekday_ppp.km
R = 0.30295, p-value &lt; 2.2e-16
alternative hypothesis: clustered (R &lt; 1)</code></pre>
</div>
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">clarkevans.test</span>(central_grab_weekend_ppp.km, <span class="at">correction=</span><span class="st">"cdf"</span>, <span class="at">alternative=</span><span class="fu">c</span>(<span class="st">"clustered"</span>), <span class="at">nsim=</span><span class="dv">99</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Clark-Evans test
    CDF correction
    Z-test

data:  central_grab_weekend_ppp.km
R = 0.41096, p-value &lt; 2.2e-16
alternative hypothesis: clustered (R &lt; 1)</code></pre>
</div>
</div>
<p>From the p-values of the Clark-Evan’s test, we have to conclude that the distributions of the Grab trip origins display clustering patterns within Singapore’s CBD regardless of the part of the week. This is a conclusion supported by our KDE plots either using <em>ppl</em> or adaptive bandwidth methods.</p>
</section>
</section>
<section id="conducting-and-analysing-network-constrained-kernel-density-estimations" class="level2">
<h2 class="anchored" data-anchor-id="conducting-and-analysing-network-constrained-kernel-density-estimations">Conducting and analysing Network-Constrained Kernel Density Estimations</h2>
<section id="limiting-the-road-network-data-to-central-singapore" class="level3">
<h3 class="anchored" data-anchor-id="limiting-the-road-network-data-to-central-singapore">Limiting the Road Network Data to Central Singapore</h3>
<p>Earlier in this report, we conducted an extraction of the road networks from <strong>OpenStreetMap</strong> using the <em>st_intersection()</em> function. We will need to do so again as we have since further limited the scope of our study to the CBD. This time however, as the purpose of using the road network data lies in constructing Network-Contrained Kernel Density Estimations, we will need to ensure that only spatial Line features exist in the data. To do so, we can employ the <em>st_cast()</em> function to coerce any other spatial features to Spatial Lines.</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>central_roads <span class="ot">&lt;-</span> <span class="fu">st_intersection</span>(roads, central_sg)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>central_roads <span class="ot">&lt;-</span> <span class="fu">st_cast</span>(central_roads, <span class="st">"LINESTRING"</span>)</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(central_roads, <span class="st">"Data/Geospatial/RDS/central_road_network.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Once again we save the spliced data for further use as it is computationally expensive.</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a>central_roads <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"Data/Geospatial/RDS/central_road_network.rds"</span>)</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>central_roads <span class="ot">&lt;-</span> <span class="fu">st_simplify</span>(central_roads, <span class="at">preserveTopology =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="visualising-the-road-network-data-across-the-cbd" class="level4">
<h4 class="anchored" data-anchor-id="visualising-the-road-network-data-across-the-cbd">Visualising the Road Network Data across the CBD</h4>
<p>Using the tm_lines() function we can build a visual plot of the road networks in the CBD</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>central_road_network_plot <span class="ot">&lt;-</span> <span class="fu">tm_shape</span>(central_sg) <span class="sc">+</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_polygons</span>(<span class="at">col =</span> <span class="st">"lightyellow"</span>) <span class="sc">+</span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">main.title =</span> <span class="st">"Road Network in Central Singapore"</span>) <span class="sc">+</span></span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(central_roads) <span class="sc">+</span></span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_lines</span>(<span class="at">col =</span> <span class="st">"brown"</span>)</span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a><span class="fu">tmap_save</span>(central_road_network_plot, <span class="st">"Screenshots/central_road_network.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><img src="Screenshots/central_road_network.png" class="img-fluid"></p>
</section>
</section>
<section id="preparing-the-lixel-objects-and-generating-the-line-centre-points" class="level3">
<h3 class="anchored" data-anchor-id="preparing-the-lixel-objects-and-generating-the-line-centre-points">Preparing the lixel objects and generating the line centre points</h3>
<p>In order to conduct NKDE, we will need to use the <em>spNetwork</em> package which requires that we parse <em>lixel</em> objects rather than <em>sf</em> objects with <em>LINESTRING</em> geometry type. Thus, we need to generate these <em>lixels</em> using the <em>lixelize_lines()</em> function. Additionally, the computation of NKDE also requires that we generate the center points of these <em>lixels</em>. This can be generated by parsing the <em>lixels</em> into the <em>lines_center()</em> function.</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>lixels <span class="ot">&lt;-</span> <span class="fu">lixelize_lines</span>(central_roads, <span class="dv">700</span>, <span class="at">mindist =</span> <span class="dv">300</span>)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>samples <span class="ot">&lt;-</span> <span class="fu">lines_center</span>(lixels)</span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(lixels, <span class="st">"Data/Geospatial/RDS/central_road_lixels.rds"</span>)</span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(samples, <span class="st">"Data/Geospatial/RDS/central_road_centrepoints.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>As the road network data is quite extensive, the computation of the <em>lixels</em> are extremely computationally expensive and time consuming. Thus, we save the generated <em>lixels</em> and <em>lixel</em> center points as RDS files also.</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>lixels <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"Data/Geospatial/RDS/central_road_lixels.rds"</span>)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>samples <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"Data/Geospatial/RDS/central_road_centrepoints.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="performing-the-network-constrained-kernel-density-estimation" class="level3">
<h3 class="anchored" data-anchor-id="performing-the-network-constrained-kernel-density-estimation">Performing the Network Constrained Kernel Density Estimation</h3>
<p>Now that we have prepared the lixels and their center points, we can run the NKDE across our 2 segmented Grab data. Our previous KDE plots provides us with some indicates of the parameters in which we can run our NKDE upon. Firstly, the kernel used should be “quartic” as we are looking for several spikes in the data whilst being less sensitive to outlier events because we know that the southern parts of the CBD are less densely serviced by Grab than the northern parts during the weekends. And even though the data is more evenly spread out in the workweek, the adaptive KDE reveals that the data exists as multiple hot-spots with strong drop-offs rather than a smooth transition to the next hot-spot. We run it on a “simple” method and set sparse to <u><em>TRUE</em></u> to reduce computation time, but also set verbose to <u><em>TRUE</em></u> to get updated that the process is running properly as the computation is expected to be very time-consuming regardless.</p>
<section id="for-the-weekday-data" class="level4">
<h4 class="anchored" data-anchor-id="for-the-weekday-data">For the Weekday Data:</h4>
<p>Using the <em>nkde()</em> function to compute the network-constrained kernel density estimates of the weekday Grab trips in the CBD:</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>weekday_densities <span class="ot">&lt;-</span> <span class="fu">nkde</span>(central_roads, </span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>                          <span class="at">events =</span> central_grab_weekday_sf,  </span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">w =</span> <span class="fu">rep</span>(<span class="dv">1</span>,<span class="fu">nrow</span>(central_grab_weekday_sf)), </span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">samples =</span> samples, </span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>                          <span class="at">kernel_name =</span> <span class="st">"quartic"</span>, </span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a>                          <span class="at">bw =</span> <span class="dv">300</span>, </span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a>                          <span class="at">div=</span> <span class="st">"bw"</span>, </span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a>                          <span class="at">method =</span> <span class="st">"simple"</span>, </span>
<span id="cb70-9"><a href="#cb70-9" aria-hidden="true" tabindex="-1"></a>                          <span class="at">digits =</span> <span class="dv">1</span>, </span>
<span id="cb70-10"><a href="#cb70-10" aria-hidden="true" tabindex="-1"></a>                          <span class="at">tol =</span> <span class="dv">1</span>, </span>
<span id="cb70-11"><a href="#cb70-11" aria-hidden="true" tabindex="-1"></a>                          <span class="at">grid_shape =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>), </span>
<span id="cb70-12"><a href="#cb70-12" aria-hidden="true" tabindex="-1"></a>                          <span class="at">max_depth =</span> <span class="dv">8</span>, </span>
<span id="cb70-13"><a href="#cb70-13" aria-hidden="true" tabindex="-1"></a>                          <span class="at">agg =</span> <span class="dv">5</span>, </span>
<span id="cb70-14"><a href="#cb70-14" aria-hidden="true" tabindex="-1"></a>                          <span class="at">sparse =</span> <span class="cn">TRUE</span>, </span>
<span id="cb70-15"><a href="#cb70-15" aria-hidden="true" tabindex="-1"></a>                          <span class="at">verbose =</span> <span class="cn">TRUE</span>)</span>
<span id="cb70-16"><a href="#cb70-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-17"><a href="#cb70-17" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(weekday_densities, <span class="st">"Data/Geospatial/RDS/Grab_weekday_nkde.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Once the density estimates are computed, we store them away as RDS files to avoid running them again unless there is a change in the data.</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>weekday_densities <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"Data/Geospatial/RDS/Grab_weekday_nkde.rds"</span>)</span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>samples<span class="sc">$</span>density <span class="ot">&lt;-</span> weekday_densities <span class="sc">*</span> <span class="dv">1000</span></span>
<span id="cb71-4"><a href="#cb71-4" aria-hidden="true" tabindex="-1"></a>lixels<span class="sc">$</span>density <span class="ot">&lt;-</span> weekday_densities <span class="sc">*</span> <span class="dv">1000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>We then reassign the computed densities to the <em>lixel</em> and <em>lixel</em> center point objects used.</p>
</section>
<section id="visualising-the-network-constrained-kernel-density-estimate-of-the-weekday-grab-data-over-an-interactive-openstreetmap-layer" class="level4">
<h4 class="anchored" data-anchor-id="visualising-the-network-constrained-kernel-density-estimate-of-the-weekday-grab-data-over-an-interactive-openstreetmap-layer">Visualising the Network Constrained Kernel Density Estimate of the Weekday Grab Data over an interactive <em>OpenStreetMap</em> layer</h4>
<p>Using the densities appended to the <em>lixels</em> generated, and the tm_lines() and tm_dots() function, we can visualise the NKDE plots. Furthermore, we shall use tm_basemap(“OpenStreetMap”) as the base layer rather than the central_sg polygons previously used. This will allow us to obtain contextualised information of the hot-spots from the NKDE produced.</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>grab_weekday_interactive <span class="ot">&lt;-</span>  <span class="fu">tm_shape</span>(lixels) <span class="sc">+</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_lines</span>(<span class="at">col=</span><span class="st">"density"</span>, <span class="at">lwd =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">frame =</span> <span class="cn">TRUE</span>, <span class="at">main.title =</span> <span class="st">"Network-Constrained Kernel Density Estimation of Grab Call Origins in the CBD"</span>) <span class="sc">+</span></span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(central_grab_weekday_sf) <span class="sc">+</span></span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>(<span class="at">col =</span> <span class="st">"green"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="fl">0.01</span>) <span class="sc">+</span></span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_scale_bar</span>() <span class="sc">+</span></span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_basemap</span>(<span class="st">"OpenStreetMap"</span>)</span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a>grab_weekday_interactive <span class="ot">&lt;-</span> <span class="fu">tmap_leaflet</span>(grab_weekday_interactive)</span>
<span id="cb72-10"><a href="#cb72-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-11"><a href="#cb72-11" aria-hidden="true" tabindex="-1"></a><span class="fu">saveWidget</span>(grab_weekday_interactive, <span class="st">"Screenshots/CBD_grab_weekday_interactive.html"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<!--html_preserve-->
<iframe src="Screenshots/CBD_grab_weekday_interactive.html" width="650" height="400">
</iframe>
<!--html_preserve-->
<p>Examining the network constrained kernel density estimation plot for Grab trips in the CBD on weekdays, we can see that there are 5 main clusters which have been formed in the following areas:</p>
<ol type="1">
<li>In Orchard, around the junctions near Orchard Ion Shopping Center.</li>
<li>Along Somerset and Orchard Roads, between Somerset and Dhoby Ghaut MRT stations.</li>
<li>Around Rochor and Bugis.</li>
<li>Chinatown</li>
<li>Raffles Place</li>
</ol>
<p>Intuitively, we this makes sense as 1. and 2. are huge shopping districts in addition to housing plenty of offices. As such, we should expect them to be frequented by tourist who may be more inclined to using Grab, as well as office workers returning home from the area after work or a night out. For hot spot 3., even though less offices are expected there, there are more nightlife spots in the area which could explain why a cluster if formed there as well.</p>
<p>The hot-spots 4. and 5. are especially strong when compared to the other 3. This is likely a result of the concentration of financial institutions and large multinational corporations concentrated in the area unlike around the other 3 clusters. Thus, an explanation for hot spots 4 and 5 would be that demand from office workers returning home either from work or a night out is strongly contributing to Grab demand in these parts of the CBD.</p>
</section>
<section id="for-the-weekend-data" class="level4">
<h4 class="anchored" data-anchor-id="for-the-weekend-data">For the Weekend Data:</h4>
<p>Using the <em>nkde()</em> function to compute the network-constrained kernel density estimates of the weekend Grab trips in the CBD:</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>weekend_densities <span class="ot">&lt;-</span> <span class="fu">nkde</span>(central_roads,</span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">events =</span> central_grab_weekend_sf,</span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">w =</span> <span class="fu">rep</span>(<span class="dv">1</span>,<span class="fu">nrow</span>(central_grab_weekend_sf)),</span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>                  <span class="at">samples =</span> samples,</span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">kernel_name =</span> <span class="st">"quartic"</span>,</span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">bw =</span> <span class="dv">300</span>,</span>
<span id="cb73-7"><a href="#cb73-7" aria-hidden="true" tabindex="-1"></a>                  <span class="at">div=</span> <span class="st">"bw"</span>,</span>
<span id="cb73-8"><a href="#cb73-8" aria-hidden="true" tabindex="-1"></a>                  <span class="at">method =</span> <span class="st">"simple"</span>,</span>
<span id="cb73-9"><a href="#cb73-9" aria-hidden="true" tabindex="-1"></a>                  <span class="at">digits =</span> <span class="dv">1</span>,</span>
<span id="cb73-10"><a href="#cb73-10" aria-hidden="true" tabindex="-1"></a>                  <span class="at">tol =</span> <span class="dv">1</span>,</span>
<span id="cb73-11"><a href="#cb73-11" aria-hidden="true" tabindex="-1"></a>                  <span class="at">grid_shape =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>),</span>
<span id="cb73-12"><a href="#cb73-12" aria-hidden="true" tabindex="-1"></a>                  <span class="at">max_depth =</span> <span class="dv">8</span>,</span>
<span id="cb73-13"><a href="#cb73-13" aria-hidden="true" tabindex="-1"></a>                  <span class="at">agg =</span> <span class="dv">5</span>,</span>
<span id="cb73-14"><a href="#cb73-14" aria-hidden="true" tabindex="-1"></a>                  <span class="at">sparse =</span> <span class="cn">TRUE</span>,</span>
<span id="cb73-15"><a href="#cb73-15" aria-hidden="true" tabindex="-1"></a>                  <span class="at">verbose =</span> <span class="cn">TRUE</span>)</span>
<span id="cb73-16"><a href="#cb73-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb73-17"><a href="#cb73-17" aria-hidden="true" tabindex="-1"></a><span class="fu">write_rds</span>(weekend_densities, <span class="st">"Data/Geospatial/RDS/Grab_weekend_nkde.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>weekend_densities <span class="ot">&lt;-</span> <span class="fu">read_rds</span>(<span class="st">"Data/Geospatial/RDS/Grab_weekend_nkde.rds"</span>)</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>samples<span class="sc">$</span>density <span class="ot">&lt;-</span> weekend_densities <span class="sc">*</span> <span class="dv">1000</span></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>lixels<span class="sc">$</span>density <span class="ot">&lt;-</span> weekend_densities <span class="sc">*</span> <span class="dv">1000</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="visualising-the-network-constrained-kernel-density-estimate-of-the-weekend-grab-data-over-an-interactive-openstreetmap-layer" class="level4">
<h4 class="anchored" data-anchor-id="visualising-the-network-constrained-kernel-density-estimate-of-the-weekend-grab-data-over-an-interactive-openstreetmap-layer">Visualising the Network Constrained Kernel Density Estimate of the Weekend Grab Data over an interactive <em>OpenStreetMap</em> layer</h4>
<p>Similarly, like in the visualisation of the weekday Grab data, we can visualise the weekend Grab data within the CBD on weekends:</p>
<div class="cell">
<details class="code-fold">
<summary>Reveal Code</summary>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>grab_weekend_interactive <span class="ot">&lt;-</span>  <span class="fu">tm_shape</span>(lixels) <span class="sc">+</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_lines</span>(<span class="at">col=</span><span class="st">"density"</span>, <span class="at">lwd =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_layout</span>(<span class="at">frame =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_shape</span>(central_grab_weekend_sf) <span class="sc">+</span></span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_dots</span>(<span class="at">col =</span> <span class="st">"green"</span>, <span class="at">alpha =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="fl">0.01</span>) <span class="sc">+</span></span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_scale_bar</span>() <span class="sc">+</span></span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tm_basemap</span>(<span class="st">"OpenStreetMap"</span>)</span>
<span id="cb75-8"><a href="#cb75-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-9"><a href="#cb75-9" aria-hidden="true" tabindex="-1"></a>grab_weekend_interactive <span class="ot">&lt;-</span> <span class="fu">tmap_leaflet</span>(grab_weekend_interactive)</span>
<span id="cb75-10"><a href="#cb75-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-11"><a href="#cb75-11" aria-hidden="true" tabindex="-1"></a><span class="fu">saveWidget</span>(grab_weekend_interactive, <span class="st">"Screenshots/CBD_grab_weekend_interactive.html"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<!--html_preserve-->
<iframe src="Screenshots/CBD_grab_weekend_interactive.html" width="650" height="400">
</iframe>
<!--html_preserve-->
<p>Looking at the network constrained kernel density estimation plot generated for Grab trips in the CBD on weekends, we cannot pin point any new and significant clusters when compared to the NKDE generated for the weekdays. There are 2 main differences however. The region around Fort Canning Park and the Esplanade appear to be slightly more dense than before, and clusters 4. and 5. have all but disappeared. It is possible that people are leaving from Fort Canning and the Esplanade more often on the weekends, but a more like cause is that the disappearance of clusters 4. and 5. and biased the NKDE computation slightly in these areas.</p>
<p>The visualisation of the weekend NKDE gives credence to the earlier suggestion that office workers are the heaviest contributors to the Grab call demand in Chinatown and Raffles Place as majority of offices are not opened on the weekends which would explain the tank in the Grab call demand.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>