---
title: "In-Class Exercise 8: Calibrating Hedonic Pricing Model for Private Highrise Property with GWR Method"
author: "Yung Qi Yang"

format: 
  html:
    code-fold: true
    code-summary: "Reveal Code"
    
execute: 
  eval: true
  echo: true
  warning: false
  
date: "`r Sys.Date()`"

toc: true
toc-location: left

progress: true
---

```{r}

pacman::p_load(olsrr, ggstatsplot, ggpubr, sf, spdep, GWmodel, tmap, tidyverse, gtsummary)

```

```{r}

mpsz = st_read(dsn = "Data/Geospatial", layer = "MP14_SUBZONE_WEB_PL")
mpsz_svy21 = mpsz %>% 
  st_transform(crs = 3414)

```

```{r}

condo_resale = read_csv("Data/Aspatial/Condo_resale_2015.csv")

condo_resale_sf <- st_as_sf(condo_resale, 
                            coords = c("LONGITUDE", "LATITUDE"),
                            crs = 4326) %>% 
  st_transform(crs = 3414)

```

```{r}

ggcorrmat(condo_resale[, 5:23])

```

```{r}

condo.mlr1 <- lm(formula = SELLING_PRICE ~ AREA_SQM + AGE    + 
                  PROX_CBD + PROX_CHILDCARE + PROX_ELDERLYCARE +
                  PROX_URA_GROWTH_AREA + PROX_HAWKER_MARKET + PROX_KINDERGARTEN + 
                  PROX_MRT  + PROX_PARK + PROX_PRIMARY_SCH + 
                  PROX_TOP_PRIMARY_SCH + PROX_SHOPPING_MALL + PROX_SUPERMARKET + 
                  PROX_BUS_STOP + NO_Of_UNITS + FAMILY_FRIENDLY + FREEHOLD, 
                data=condo_resale_sf)

summary(condo.mlr1)

```

```{r}

tbl_regression(condo.mlr1, 
               intercept = TRUE)

```

```{r}

tbl_regression(condo.mlr1, 
               intercept = TRUE) %>% 
  add_glance_source_note(
    label = list(sigma ~ "\U03C3"),
    include = c(r.squared, adj.r.squared, 
                AIC, statistic,
                p.value, sigma))

```




```{r}

mlr.p <- ggcoefstats(condo.mlr1)
mlr.p

```

```{r}

mlr.p <- ggcoefstats(condo.mlr1,
                     sort = "ascending")
mlr.p

```

```{r}

ols_vif_tol(condo.mlr1)

```

```{r}

ols_plot_resid_fit(condo.mlr1)

```

```{r}

ols_plot_resid_hist(condo.mlr1)

```

```{r}

ols_test_normality(condo.mlr1)

```

```{r}

mlr.output <- as.data.frame(condo.mlr1$residuals)

condo_resale.res_sf <- cbind(condo_resale_sf, 
                        condo.mlr1$residuals) %>% 
  rename(`MLR_RES` = `condo.mlr1.residuals`)

condo_resale_sp <- as_Spatial(condo_resale_sf)
condo_resale_sp

```

```{r}

tmap_mode("view")

tm_shape(mpsz_svy21)+
  tmap_options(check.and.fix = TRUE) +
  tm_polygons(alpha = 0.4) +
tm_shape(condo_resale.res_sf) +  
  tm_dots(col = "MLR_RES",
          alpha = 0.6,
          style="quantile") +
  tm_view(set.zoom.limits = c(11,14))

tmap_mode("plot")

```


```{r}

nb <- dnearneigh(coordinates(condo_resale_sp), 0, 1500, longlat = FALSE)
summary(nb)

nb_lw <- nb2listw(nb, style = 'W')
summary(nb_lw)

lm.morantest(condo.mlr1, nb_lw)

```


```{r}

bw.fixed <- bw.gwr(formula = SELLING_PRICE ~ AREA_SQM + AGE + PROX_CBD + 
                     PROX_CHILDCARE + PROX_ELDERLYCARE + PROX_URA_GROWTH_AREA + 
                     PROX_MRT + PROX_PARK + PROX_PRIMARY_SCH + 
                     PROX_SHOPPING_MALL + PROX_BUS_STOP + NO_Of_UNITS + 
                     FAMILY_FRIENDLY + FREEHOLD, 
                   data= condo_resale_sp, 
                   approach="CV", 
                   kernel="gaussian", 
                   adaptive=FALSE, 
                   longlat=FALSE)

```

```{r}

gwr.fixed <- gwr.basic(formula = SELLING_PRICE ~ AREA_SQM + AGE + PROX_CBD + 
                         PROX_CHILDCARE + PROX_ELDERLYCARE  + PROX_URA_GROWTH_AREA + 
                         PROX_MRT  + PROX_PARK + PROX_PRIMARY_SCH + 
                         PROX_SHOPPING_MALL + PROX_BUS_STOP + NO_Of_UNITS + 
                         FAMILY_FRIENDLY + FREEHOLD, 
                       data=condo_resale_sp, 
                       bw=bw.fixed, 
                       kernel = 'gaussian', 
                       longlat = FALSE)

gwr.fixed

```

```{r}

bw.adaptive <- bw.gwr(formula = SELLING_PRICE ~ AREA_SQM + AGE  + 
                        PROX_CBD + PROX_CHILDCARE + PROX_ELDERLYCARE    + 
                        PROX_URA_GROWTH_AREA + PROX_MRT + PROX_PARK + 
                        PROX_PRIMARY_SCH + PROX_SHOPPING_MALL   + PROX_BUS_STOP + 
                        NO_Of_UNITS + FAMILY_FRIENDLY + FREEHOLD, 
                      data=condo_resale_sp, 
                      approach="CV", 
                      kernel="gaussian", 
                      adaptive=TRUE, 
                      longlat=FALSE)

gwr.adaptive <- gwr.basic(formula = SELLING_PRICE ~ AREA_SQM + AGE + 
                            PROX_CBD + PROX_CHILDCARE + PROX_ELDERLYCARE + 
                            PROX_URA_GROWTH_AREA + PROX_MRT + PROX_PARK + 
                            PROX_PRIMARY_SCH + PROX_SHOPPING_MALL + PROX_BUS_STOP + 
                            NO_Of_UNITS + FAMILY_FRIENDLY + FREEHOLD, 
                          data=condo_resale_sp,
                          bw=bw.adaptive, 
                          kernel = 'gaussian', 
                          adaptive=TRUE, 
                          longlat = FALSE)

gwr.adaptive

```

```{r}

condo_resale_sf.adaptive <- st_as_sf(gwr.adaptive$SDF) %>%
  st_transform(crs = 3414)

condo_resale_sf.adaptive.svy21 <- st_transform(condo_resale_sf.adaptive, 3414)
condo_resale_sf.adaptive.svy21

```

```{r}

gwr.adaptive.output <- as.data.frame(gwr.adaptive$SDF)
condo_resale_sf.adaptive <- cbind(condo_resale.res_sf, as.matrix(gwr.adaptive.output))

glimpse(condo_resale_sf.adaptive)

```

```{r}

tmap_mode("view")

tm_shape(mpsz_svy21)+
  tm_polygons(alpha = 0.1) +
tm_shape(condo_resale_sf.adaptive) +  
  tm_dots(col = "Local_R2",
          border.col = "gray60",
          border.lwd = 1) +
  tm_view(set.zoom.limits = c(11,14))

```

```{r}

AREA_SQM_SE <- tm_shape(mpsz_svy21)+
  tm_polygons(alpha = 0.1) +
tm_shape(condo_resale_sf.adaptive) +  
  tm_dots(col = "AREA_SQM_SE",
          border.col = "gray60",
          border.lwd = 1) +
  tm_view(set.zoom.limits = c(11,14))

AREA_SQM_TV <- tm_shape(mpsz_svy21)+
  tm_polygons(alpha = 0.1) +
tm_shape(condo_resale_sf.adaptive) +  
  tm_dots(col = "AREA_SQM_TV",
          border.col = "gray60",
          border.lwd = 1) +
  tm_view(set.zoom.limits = c(11,14))

tmap_arrange(AREA_SQM_SE, AREA_SQM_TV, 
             asp=1, ncol=2,
             sync = TRUE)

```

```{r}

tmap_mode("plot")

tm_shape(mpsz_svy21[mpsz_svy21$REGION_N=="CENTRAL REGION", ])+
  tm_polygons()+
tm_shape(condo_resale_sf.adaptive) + 
  tm_bubbles(col = "Local_R2",
           size = 0.15,
           border.col = "gray60",
           border.lwd = 1)

```

