---
title: "Take-Home Exercise 1: Application of Spatial Point Patterns Analysis to discover the geographical distribution of Grab's hailing services in Singapore"
author: "Yung Qi Yang"

format: 
  html:
    code-fold: true
    code-summary: "Reveal Code"
    
execute: 
  eval: true
  echo: true
  warning: false
date: "`r Sys.Date()`"

toc: true
toc-location: left

progress: true
---

### Loading the necessary R-packages

```{r}

pacman::p_load(sf, tidyverse, arrow, lubridate, tmap)

```

### Importing the datasets of interest

#### Grab-Posisi Data:

```{r}
#| eval: false

grab_df <- read_parquet("Data/Geospatial/GrabPosisi/part-00000-8bbff892-97d2-4011-9961-703e38972569.c000.snappy.parquet")

for (i in 1:9) {
  grab_df <- grab_df %>%
    rbind(read_parquet(paste0("Data/Geospatial/GrabPosisi/part-0000", as.character(i), "-8bbff892-97d2-4011-9961-703e38972569.c000.snappy.parquet")))
}

glimpse(grab_df)

write_parquet(grab_df, "Data/Geospatial/GrabPosisi/Grab_Posisi.parquet")

```
##### Grab-Posisi Data 


```{r}
#| eval: false

grab_origin_df <- grab_df %>% 
  group_by(trj_id) %>% 
  arrange(pingtimestamp) %>% 
  filter(row_number() == 1) %>% 
  mutate(weekday = wday(pingtimestamp, label = TRUE, abbr = TRUE), start_hr = factor(hour(pingtimestamp)), day = factor(mday(pingtimestamp)))

glimpse(grab_origin_df)

write_rds(grab_origin_df, "Data/Geospatial/RDS/Grab_Origins_Posisi.rds")

```

```{r}
#| eval: false

grab_dest_df <- grab_df %>% 
  group_by(trj_id) %>% 
  arrange(desc(pingtimestamp)) %>% 
  filter(row_number() == 1) %>% 
  mutate(weekday = wday(pingtimestamp, label = TRUE, abbr = TRUE), start_hr = factor(hour(pingtimestamp)), day = factor(mday(pingtimestamp)))

glimpse(grab_dest_df)

write_rds(grab_dest_df, "Data/Geospatial/RDS/Grab_Dest_Posisi.rds")

```


```{r}
#| eval: false

grab_df <- read_parquet("Data/Geospatial/GrabPosisi/Grab_Posisi.parquet")

glimpse(grab_df)
summary(grab_df)

```


#### LTA Data:

```{r}



```
