---
title: "Hands-On Exercise 1: Geospatial Data Wrangling with R"

author: "Yung Qi Yang"
format: 
  html:
    code-tools: true
    code-fold: true
    code-summary: "Reveal Code"
    
execute: 
  eval: true
  echo: true
  warning: false
date: "`r Sys.Date()`"

code-annotations: select
---

## Getting Started

## 1.3

```{r}

#Installing the pacman package
#install.packages('pacman')
pacman::p_load(sf, tidyverse) 

```

#1.4

```{r}

#1.4.1
mpsz = st_read(dsn = "Data/Geospatial/Master Plan", 
               layer = "MP14_SUBZONE_WEB_PL")

#1.4.2
cyclingpath = st_read(dsn = "Data/Geospatial/CyclingPath", 
                      layer = "CyclingPathGazette")

#1.4.3
preschool = st_read("Data/Geospatial/Pre-School Location/PreSchoolsLocation.kml")

```

#1.5

```{r}

#1.5.1
st_geometry(mpsz)

#1.5.2
glimpse(mpsz)

#1.5.3
head(mpsz, n = 5)

```

#1.6

```{r}


plot(mpsz)

plot(st_geometry(mpsz))

plot(mpsz["PLN_AREA_N"])

```

#1.7

```{r}

#1.7.1
st_crs(mpsz)
mpsz3414 <- st_set_crs(mpsz, 3414)
st_crs(mpsz3414)

#1.7.2
preschool3414 <- st_transform(preschool, 
                              crs = 3414)

```

#1.8

```{r}

#1.8.1
listings <- read_csv("Data/Aspatial/Airbnb Listing/listings.csv")
list(listings)

#1.8.2
listings_sf <- st_as_sf(listings, 
                        coords = c("longitude", "latitude"), 
                        crs=4326) %>%
  st_transform(crs = 3414)

glimpse(listings_sf)

```

#1.9

```{r}

#1.9.1
buffer_cycling <- st_buffer(cyclingpath, 
                            dist=5, nQuadSegs = 30)

buffer_cycling$AREA <- st_area(buffer_cycling)
sum(buffer_cycling$AREA)

#1.9.2
mpsz3414$`PreSch Count`<- lengths(st_intersects(mpsz3414, preschool3414))
summary(mpsz3414$`PreSch Count`)

top_n(mpsz3414, 1, `PreSch Count`)
mpsz3414$Area <- mpsz3414 %>% 
  st_area()

mpsz3414 <- mpsz3414 %>% 
  mutate(`PreSch Density` = `PreSch Count`/Area * 1000000)

```

#1.10

```{r}

hist(mpsz3414$`PreSch Density`)

ggplot(data=mpsz3414, 
       aes(x= as.numeric(`PreSch Density`)))+
  geom_histogram(bins=20, 
                 color="black", 
                 fill="light blue") + 
  labs(title = "Are pre-school even distributed in Singapore?",
       subtitle= "There are many planning sub-zones with a single pre-school, on the other hand, \nthere are two planning sub-zones with at least 20 pre-schools", 
       x = "Pre-school density (per km sq)", 
       y = "Frequency")

ggplot(data=mpsz3414, 
       aes(y = `PreSch Count`, 
           x= as.numeric(`PreSch Density`))) + 
  geom_point(color="black", 
             fill="light blue") + 
  xlim(0, 40) + 
  ylim(0, 40) +
  labs(title = "", 
       x = "Pre-school density (per km sq)", 
       y = "Pre-school count")

```
